# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: autocorrect-fix
        name: autocorrect fix
        description: "Fixes the style of CJK files."
        entry: autocorrect --fix
        language: system
        types: [file]
